<?php /** @var \Magento\Framework\View\Element\Template $block */?>

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magento_Cms::css/tiny-slider.css')?>">

<div class="mainpageCarusele">

    <div class="my-slider">
        <div>
            <div class="firstBanner">
                <div class="firstBanner__content">
                    <div class="firstBanner__content--title">
                        Sale
                    </div>
                    <div class="firstBanner__content--info">
                        UP TO 70%
                    </div>
                </div>
            </div>
           
        </div>
        <div>
            <a href="#">
                <div>The best clothes and accessories on the web</div>
            </a>
        </div>
        <div>3</div>
    </div>

</div>

<script>
    (function  () {
        require(["tns"],function() {
            var slider = tns({
                container: '.my-slider',
                items: 1,
                nav: false,
                controlsText: ["<",">"],
                autoHeight:true,

            });
        });
    })();
</script>