<?php /** @var \Magento\Framework\View\Element\Template $block */?>

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('css/tiny-slider.css')?>">

<div class="mainpageCarusele">

    <div class="my-slider">
        <div>
            <div class="firstBanner">
                <div class="firstBanner__content">
                    <div class="firstBanner__content--title">
                        Sale
                    </div>
                    <div class="firstBanner__content--info">
                        UP TO 70%
                    </div>
                </div>
            </div>
           
        </div>
        <div>
            <div class="secondBanner">
                <p class="secondBanner__title">THE BEST CLOTHES AND ACCESSORIES <br /> ON THE WEB</p>
                <div class="secondBanner__buttonsContaner">
                    
                    <div class="secondBanner__buttonContaner">
                        <a href="#"> 
                            <div class="secondBanner__buttonContaner--button">                            
                                <p class="secondBannerButtonContent">SHOP CLOTHES</p>
                            </div>
                        </a>
                    </div>
                    <div class="secondBanner__buttonContaner">
                        <a href="#">
                            <div class="secondBanner__buttonContaner--button">
                                <p class="secondBannerButtonContent">SHOP ACCESSORIES</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="thirdBanner">
                <div class="thirdBannerContent">
                    <a href="#">
                        <p class="thirdBannerContent__title">New collection of Nike shoes</p>
                        <p class="thirdBannerContent__info">Prices start at $80 </p>
                    </a>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    (function  () {
        require(["tns"],function() {
            var slider = tns({
                container: '.my-slider',
                items: 1,
                nav: false,
                controlsText: ["<",">"],
                autoHeight:true,
                autoplay:true,
                autoplayHoverPause: true,
                rewind: true,
                autoplayButtonOutput: false

            });
        });
    })();
</script>