<?php /** @var \Magento\Framework\View\Element\Template $block */?>

<div class="promoBlocks">
    <div class="firstPromoBlock">
        <div class="firstPromoBlock__content">
            <p class="firstPromoBlock__content--text">FAST DELIVERY</p>
            <p class="firstPromoBlock__content--plus">+</p>
            <p class="firstPromoBlock__content--text">SHIPPING WORLDWIDE</p>
            <p class="firstPromoBlock__content--plus">+</p>
            <p class="firstPromoBlock__content--text">BEST PRICES</p>
          
        </div>
        <div class="firstPromoBlock__photo">
            
        </div>
    </div>
    <div class="secondPromoBlock">
        <div class="secondPromoBlock__photo">

        </div>
        <div class="secondPromoBlock__content">
            <p class="secondPromoBlock__content--info"> Always the latest collections, at the best prices</p>
            <p class="secondPromoBlock__content--text">TRUST US</p> 
        </div>
    </div>
</div>