<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                        <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php $i = 0; ?>  <!-- MY PHP CODE -->
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php $i++ ?> <!-- MY PHP CODE -->
                    <?php if (!$wrapOptions) : ?>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false
                            }
                        }'>
                        <?php $wrapOptions = true;
                        endif; ?>
                         <div data-role="collapsible" class="filter-options-item" id="item-number<?= $block->escapeHtmlAttr($i) ?>" onClick="changeSpanInFilterOptions(this.id);"> <!-- MY PHP CODE -->
                            <div data-role="title" class="filter-options-title" ><?= $block->escapeHtml(__($filter->getName())) ?> 
                                <span class="filer-options-span" id="item-number-span<?= $block->escapeHtmlAttr($i) ?>">+</span><!-- MY PHP CODE -->
                            </div>
                            <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                        </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script>
function changeSpanInFilterOptions(itemId){
    const numberOfOptionsItem = itemId.replace(/\D/g, "");
    const spanOfOptionsItem = document.getElementById(`item-number-span${numberOfOptionsItem}`);
    console.log(spanOfOptionsItem);
    if (spanOfOptionsItem.innerHTML === "+")
    {
        spanOfOptionsItem.innerHTML = '-';
    }
    else {
        spanOfOptionsItem.innerHTML = '+';
    }   
}
</script>
