<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php $index = 0; ?>  
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php $index++ ?> 
                <?php if (!$wrapOptions) : ?>
                    <dl class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <div class="filter-options-container" id="item-number<?= $block->escapeHtmlAttr($index) ?>" onClick="unfoldNavMenuItem(this);"> 
                            <div role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?>
                                <span class="filer-options-span" id="item-number-span<?= $block->escapeHtmlAttr($index) ?>">+</span>
                            </div>
                            <div class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                        </div>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>


<script>
function unfoldNavMenuItem(element){
    const numberOfOptionsItem = element.id.replace(/\D/g, "");
    const spanOfOptionsItem = document.getElementById(`item-number-span${numberOfOptionsItem}`);
    if (spanOfOptionsItem.innerHTML === "+")
    {
        spanOfOptionsItem.innerHTML = '-';
        element.classList.add("collapsed")
    }
    else {
        spanOfOptionsItem.innerHTML = '+';
        element.classList.remove("collapsed")
    }   
}
</script>
