<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <?php $index = 0; ?>  
        <div>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <?php if ($alias != "reviews") :?>
                    <?php $index++ ?>
                    <div class="productInfoContainer" id="info-label-number<?= $block->escapeHtmlAttr($index)?>" onClick="unfoldInfoLabel(this);">
                        <div class="productInfoContainer__header">
                                <?= /* @noEscape */ $label ?>
                        </div>
                        <div class="productInfoContainer__info">
                            <?= /* @noEscape */ $html ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>


<script>
function unfoldInfoLabel(item){
    const numberOfInfoItem = item.id.replace(/\D/g, "");
    if (item.classList.contains("collapsed"))
    {
        item.classList.remove("collapsed")
    }
    else {
        item.classList.add("collapsed")
    }   
}
</script>
