<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <?php if ($alias == "reviews") :?>
                    <div class="data item title"
                        data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                        <div class="data switch">
                            <?= /* @noEscape */ $label ?>
                    </div>
                    </div>
                    <div class="data item content"
                        aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                        <?= /* @noEscape */ $html ?>
                    </div>
                <?php endif; ?>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>

<script>
    //  I know that PHP will suit better for this purpose but I can't do it in it
    (() =>{
        let i = 0

        let reviewsInterval= setInterval (() => {
            const reviewContainer = document.getElementById("product-review-container");
            if (reviewContainer.innerHTML === "")
            {
                reviewContainer.innerHTML = 
                `<div class="no-reviews"> 
                    <p class="no-reviews-info">We don't have any reviews</p>
                    <p class="no-reviews-info">Leave Yours</p>
                    <p id="reviews-arrow">&#8680;</p>

                </div>`
            }
            // I think that 15 sec should be enough to load comments
            if (++i === 15 ){
                window.clearInterval(reviewsInterval);
            }    
        },1000);
    })();

</script>

