<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>


    <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('css/tiny-slider.css')?>">


    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <div class="product-items products-slider <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<div class="product-item">' : '</div><div class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>


                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>


<script>
    (function  () {
        require(["tns"],function() {
            var slider = tns({
                container: '.products-slider',
                items: 1,
                slideBy: 1,
                nav: false,
                controlsText: ["<",">"],

                responsive: {
                    300 : {
                        items:2,
                        slideBy:2,
                    },
                    500: {
                        items:4,
                        slideBy:4,
                    }
                }
            });
        });
    })();

</script>